"use strict";

import { Connection, Keypair, PublicKey, Transaction, SystemProgram, sendAndConfirmTransaction } from "@solana/web3.js";
import { Program, AnchorProvider, Idl, BN } from "@coral-xyz/anchor";

// Placeholder - will be updated after program deployment
const PROGRAM_ID = new PublicKey("Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS");

// Initialize Solana connection (Devnet)
const connection = new Connection("https://api.devnet.solana.com", "confirmed");

/**
 * Initialize Anchor program client
 * @param wallet Keypair for the authority wallet
 * @returns Configured Anchor program
 */
export async function initSolanaClient(wallet: Keypair): Promise<Program> {
    const provider = new AnchorProvider(
        connection,
        new (AnchorProvider as any).wallet(wallet),
        { preflightCommitment: "confirmed" }
    );
    
    // Load program (IDL will be generated by Anchor)
    const idl = require("./idl/valhalla_settlement.json") as Idl;
    const program = new (Program as any)(idl, PROGRAM_ID, provider) as Program;
    
    return program;
}

/**
 * Generate a PDA for a trade batch
 * @param batchId Unique identifier for the batch
 * @returns PDA public key and bump seed
 */
export async function getBatchPDA(batchId: string): Promise<[PublicKey, number]> {
    return await PublicKey.findProgramAddress(
        [Buffer.from("valhalla_batch"), Buffer.from(batchId)],
        PROGRAM_ID
    );
}

/**
 * Submit a trade batch settlement to Solana
 * @param params Settlement parameters
 * @returns Transaction signature
 */
export async function submitTradeBatchSettlement(params: {
    authority: Keypair;
    batchId: string;
    matchedHash: Buffer;
    winner: PublicKey;
    loser: PublicKey;
    amountSoc: number;
    escrowWallet: PublicKey;
    treasuryWallet: PublicKey;
}): Promise<string> {
    // Initialize program
    const program = await initSolanaClient(params.authority);
    
    // Get batch PDA
    const [batchPDA, bump] = await getBatchPDA(params.batchId);
    
    // Create transaction
    const tx = new Transaction().add(
        await program.methods.anchorTradeBatch(
            params.batchId,
            Array.from(params.matchedHash),
            params.winner,
            params.loser,
            new BN(params.amountSoc)
        )
        .accounts({
            batch: batchPDA,
            escrowWallet: params.escrowWallet,
            winnerWallet: params.winner,
            treasuryWallet: params.treasuryWallet,
            authority: params.authority.publicKey,
            systemProgram: SystemProgram.programId,
        })
        .instruction()
    );
    
    // Send and confirm transaction
    const signature = await sendAndConfirmTransaction(
        connection,
        tx,
        [params.authority]
    );
    
    return signature;
}

/**
 * Generate a SHA-256 hash of matched pairs for batch verification
 * @param matchedPairs Array of matched pairs
 * @returns 32-byte hash
 */
export async function generateMatchedPairsHash(matchedPairs: Array<{
    buyOrderId: number;
    sellOrderId: number;
    matchedPrice: number;
    matchedSize: number;
    pnl: number;
}>): Promise<Buffer> {
    const crypto = require("crypto");
    
    // Create a sorted, stringified representation of the matched pairs
    const pairsString = matchedPairs
        .map(pair => `
            ${pair.buyOrderId}:${pair.sellOrderId}:${pair.matchedPrice}:
            ${pair.matchedSize}:${pair.pnl}
        `)
        .sort()
        .join("");
    
    // Generate SHA-256 hash
    return crypto.createHash("sha256").update(pairsString).digest();
}

/**
 * Fetch batch settlement proof from Solana
 * @param batchId Batch identifier
 * @returns Batch account data or null if not found
 */
export async function getBatchSettlementProof(batchId: string): Promise<any | null> {
    const program = await initSolanaClient(Keypair.generate()); // Temporary keypair
    const [batchPDA] = await getBatchPDA(batchId);
    
    try {
        const batchAccount = await (program.account as any).batch.fetch(batchPDA);
        return batchAccount;
    } catch (error) {
        if ((error as Error).message.includes("Account does not exist")) {
            return null;
        }
        throw error;
    }
}
